name: PHP Composer

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.json'
      - '**.xml' # Because there is an .xml in the SQL directory 
      - '**.xsd'
      - '**.txt'
      - '**.log'
      - '.gitignore'

jobs:
  Tag-Commit:
    needs: [TEST-Powershell, TEST-pwsh]
    runs-on: windows-latest # On windows VM

    steps:
    - uses: actions/checkout@v2

    - name: Retrieve all branches and tags
      shell: pwsh
      run: |
        git fetch --prune --unshallow --tags
    - name: Set new tag
      shell: pwsh
      run: |
        if(Test-Path .\.github\tagging)
        {
          git clone https://github.com/BrandonMFong/xPro.git
          [string]$repodir = $(pwd).path;
          [string]$SetTagPath = $repodir + "\xPro\Functions\DetermineTagType.ps1";
          $env:GIT_REDIRECT_STDERR = '2>&1';
          & $SetTagPath -Push:$true -PathToVersionConfig:$("$($repodir)\.github\tagging\Version.json") -PathToTag:$($repodir);
        }
