name: PHP Composer

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.json'
      - '**.xml' # Because there is an .xml in the SQL directory 
      - '**.xsd'
      - '**.txt'
      - '**.log'
      - '.gitignore'

jobs:
  Auto-Tagging:
    runs-on: windows-latest # On windows VM

    steps:
    - uses: actions/checkout@v2

    - name: Retrieve all branches and tags
      shell: pwsh
      run: |
        git fetch --prune --unshallow --tags

    - name: Set new tag
      shell: pwsh
      run: |
        if(Test-Path .\.github\tagging)
        {
          git clone https://github.com/BrandonMFong/xPro.git
          cd xPro; # TODO delete
          git branch -a; # TODO delete
          git checkout --track origin/release-dev-Version4 # TODO delete
          ls .; # TODO delete
          cd .. # TODO delete

          [string]$repodir = $(pwd).path;
          [string]$ProfileScript = $repodir + "\xPro\Profile.ps1";
          [string]$SetTagPath = $repodir + "\xPro\Functions\DetermineTagType.ps1";
          [string]$PathToAutoGit = $repodir + ".\xPro\.github\tagging\Profile.xml";

          & $ProfileScript -BuildPath:$PathToAutoGit -Silent:$true;
          $env:GIT_REDIRECT_STDERR = '2>&1';
          & $SetTagPath -Push:$true -PathToVersionConfig:$("$($repodir)\.github\tagging\Version.json") -PathToTag:$($repodir);
        }
